module.exports = [
    {
        name: 'development',
        type: 'sqlite',
        database: 'database.sqlite',
        synchronize: true,
        logging: true,
        entities: ['src/entity/**/*.ts'],
        migrations: ['src/migration/**/*.ts'],
        subscribers: ['src/subscriber/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/migration',
            subscribersDir: 'src/subscriber',
        },
    },
    {
        name: 'development_mariadb',
        type: 'mysql',
        host: 'teldrassil.pedrocarmo.pt',
        port: 9025,
        username: 'root',
        password: 'root',
        database: 'moviestest',
        synchronize: true,
        logging: false,
        entities: ['src/entity/**/*.ts'],
        migrations: ['src/migration/**/*.ts'],
        subscribers: ['src/subscriber/**/*.ts'],
    },
    {
        name: 'development_postgres',
        type: 'postgres',
        host: 'localhost',
        port: 15432,
        username: 'postgres',
        password: 'Postgres2019!',
        database: 'movietest',
        synchronize: true,
        logging: true,
        entities: ['src/entity/*.*'],
    },
    {
        name: 'production',
        type: 'postgres',
        url: process.env.DATABASE_URL,
        synchronize: true, // switch this to false once you have the initial tables created and use migrations instead
        logging: false,
        entities: ['dist/entity/**/*.js'],
        migrations: ['dist/migration/**/*.js'],
        subscribers: ['dist/subscriber/**/*.js'],
        cli: {
            entitiesDir: 'dist/entity',
            migrationsDir: 'dist/migration',
            subscribersDir: 'dist/subscriber',
        },
    },
];
